-- Seed initial products into Supabase. Run once in SQL Editor after schema.sql.
-- Matches src/data/products.ts so the migration is a no-op for shoppers.

insert into products (slug, name, price_cents, description, colors, tags, featured, sold_out, sort_order) values
('sunset-stripe', 'Sunset Stripe', 1200,
 'Warm coral, peach, and gold glass beads — like a sky right before the sun dips down. Stretchy cord fits wrists 5½"–7".',
 array['#ff8a65','#ffd180','#f4a261'],
 array['everyday','warm-tones'],
 true, true, 10),
('ocean-drops', 'Ocean Drops', 1400,
 'Translucent sea-blue beads with a tiny silver starfish charm. A little splash of summer on your wrist.',
 array['#4fc3f7','#81d4fa','#b3e5fc'],
 array['charm','cool-tones'],
 true, true, 20),
('berry-party', 'Berry Party', 1200,
 'Raspberry, blueberry, and blackberry beads in a mix-and-match pattern. Fun, punchy, and very fruity.',
 array['#e91e63','#7e57c2','#5e35b1'],
 array['everyday','bold'],
 true, true, 30),
('mint-cream', 'Mint & Cream', 1300,
 'Soft mint green paired with creamy pearl beads and a single gold letter bead (we''ll pick one at random — surprise!).',
 array['#a5d6a7','#fff8e1','#e8f5e9'],
 array['pastel','letter-bead'],
 false, true, 40),
('midnight-sparkle', 'Midnight Sparkle', 1500,
 'Deep navy beads, tiny silver seed beads, and a crystal star. Looks especially great on date nights and school dances.',
 array['#1a237e','#b0bec5','#eceff1'],
 array['charm','evening'],
 true, true, 50),
('bff-duo', 'BFF Duo (set of 2)', 2000,
 'Two matching bracelets — one for you, one for your best friend. Pink and lavender with heart charms. Ships as a pair.',
 array['#f8bbd0','#d1c4e9','#fce4ec'],
 array['set','friendship'],
 false, true, 60),
('rainbow-stack', 'Rainbow Stack (set of 3)', 2500,
 'Three stretchy bracelets in red/orange/yellow, green/blue, and purple/pink. Wear one, wear them all.',
 array['#ef5350','#42a5f5','#ab47bc'],
 array['set','bold'],
 false, true, 70),
('forest-walk', 'Forest Walk', 1300,
 'Earthy wood beads, moss-green glass, and a tiny leaf charm. For anyone who likes being outside.',
 array['#8d6e63','#689f38','#a1887f'],
 array['charm','earth-tones'],
 false, true, 80)
on conflict (slug) do nothing;
